### ISSUE TITLE
Permission denied experienced when following the docs 

### ISSUE THREAD

**Issue by pgc1a** [Azure/mock-spacestation#18]
**Description**
Permissions issue when following docs to create the sync file 

**Steps to Reproduce**
2) creating the hello.txt led to permission denied, it was already there and syncing properly as far as I can tell... azureuser@mockSpacestation:~$ echo "Hello! It is currently $(date) on the mockSpacestation! Happy Hacking!" >> /home/azureuser/trials/hello.txt
-bash: /home/azureuser/trials/hello.txt: Permission denied;

**Expected behavior**
Follow docs without encountering errors 

**Actual behavior**
N/A

**Additional context**
Let's add a recursive flag to the chown (so it'd be chown -R azureuser /home/azureuser/trials) and that should take care of both the permission denied and allow the user to overwrite the value if they follow the docs verbatim. Let's keep something in there by default so that we know the crontab registered. Make that change here: https://github.com/Azure/mock-spacestation/blob/main/scripts/configureSource.sh#L17

**Comment by glennmusa** [comment]
Verified, thanks @pgc1a!
