### ISSUE TITLE
[Doc Improvement] Include properties for groundstationLocation and spacestationLocation in CLI setup instructions

### ISSUE THREAD

**Issue by dave-read** [Azure/mock-spacestation#23]
**Is your feature request related to a problem? Please describe.**

I needed to deploy the sample to other clouds/regions that the defaults.  I could see in the portal screen shots that those values are parameters, but I didn't see them in the CLI instructions/example.  It was not difficult to find the parameters in the bicep template, but I think it would not be uncommon to need to deploy to other clouds/regions so listing those in the setup steps for the CLI would be helpful.

**Describe the solution you'd like**

Include the two location properties in the CLI example for cases where default location are not available/appropriate, or just note the names.

```
export groundstationLocation=usgovvirginia
export spacestationLocation=usgovarizona

az group create \
  --location $groundstationLocation \
  --name $resourceGroupName

az deployment group create \
--resource-group $resourceGroupName \
--name $deploymentName \
--parameters groundstationLocation=$groundstationLocation \
--parameters spacestationLocation=$spacestationLocation \
--template-file ./mockSpacestation.bicep
```

**Describe alternatives you've considered**
I created a local deployment script as noted above.

**Additional context**

The existing docs/examples are a very good start.  You might want to add a specific issue category for doc related issues/suggestions.

If you agree this is a reasonable change I'm happy to create a PR for suggested change.

**Comment by glennmusa** [comment]
Doc changes make sense to me. Totally welcome a PR! It'd be nice to have these helpful commands. Complete transparency, never designed or tested to see if a deployment works in AzureUsGovernment.

We should still strive to keep the root README as simple as possible and to the bare minimum required to deploy as the first thing users see.

I could see a new section in the docs `Deploy to Azure Government` that has both: 
- a .json template embedded with the right defaults to light up a `Deploy to Azure Gov` button that renders the Portal experience
- _and_ the docs you described above. What do you think?

**Comment by dave-read** [comment]
Other than region names, the existing template deploys fine to GovCoud.  So I think just a note with pointer to docs would be enough of a heads up for a general note deploying to other clouds/regions. 

https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-welcome

I'll create a PR with that and if it's too heavy for the root README
