### ISSUE TITLE
Execution perms for getConnections.sh

### ISSUE THREAD

**Issue by daweins** [Azure/mock-spacestation#3]
Trying this out in code spaces, I can't execute getConnections.sh immediately, as the file doesn't have exec permissions, and sudo doesn't exist in code spaces. We should fix this either in permissions (if possible), or document a chmod step in Code Spaces. 

![image](https://user-images.githubusercontent.com/31543514/130301510-d0e2ee16-c03d-489b-994f-3922a3285c61.png)

Not a blocker for go-live

**Comment by glennmusa** [comment]
Ah, definitely a mistake on my part. Fixed, let me know if it persists with a fresh pull/fresh container.
